import Head from "next/head";
import { useState } from "react";

import Navbar from "../components/Navbar";
import Aboutme from "../components/Aboutme";
import Projects from "../components/Projects";
import Technology from "../components/Technology";
import Testimonial from "../components/Testimonial";
import Footer from "../components/Footer";

export default function Home() {
  const [darkMode, setDrakMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Junaid-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-portfolio.png" />
      </Head>

      <main className="dark:bg-slate-800 dark:text-white">
        <Navbar setDrakMode={setDrakMode} darkMode={darkMode} />
        <Aboutme />
        <Projects />
        <Technology />
        <Testimonial />
        <Footer />
      </main>
    </div>
  );
}
